/* -------------------------------------------------------
 * MCI Screening — Clinical Screening
 * Model: 24-month MCI → Alzheimer's disease progression
 *
 * Mirrors:
 *   - MCIScreeningInput
 *   - MCIScreeningOutput
 * ----------------------------------------------------- */

/* ======================================================
 * Enums
 * ====================================================== */

export type PredictionStatus =
  | "success"
  | "error"
  | "partial";

export type MCIScreeningRiskCategory =
  | "LOW"
  | "INTERMEDIATE"
  | "HIGH";

export type MCIScreeningRecommendedNextStep =
  | "ROUTINE_MONITORING"
  | "CONSIDER_ADDITIONAL_EVALUATION"
  | "COMPREHENSIVE_AD_ASSESSMENT";

/* ======================================================
 * Shared Prediction Metadata
 * Mirrors PredictionResponseBase
 * ====================================================== */

export interface PredictionResponseBase {
  /** Assessment ID generated by Supabase */
  assessment_id?: string;
  /** Model version */
  model_version: string;
  /** Prediction execution status */
  status: PredictionStatus;
  /** Error message if prediction failed */
  error?: string;
  /** Non-fatal warnings */
  warnings?: string[];
  /** Optional confidence interval */
  confidence_interval?: [number, number];
  /** UTC timestamp */
  timestamp: string;
}

/* ======================================================
 * Input
 * Mirrors MCIScreeningInput
 * ====================================================== */

export interface MCIScreeningInput {
  /** Optional patient identifier */
  patient_id?: string | number;
  /** Age (years) */
  AGE: number;
  /** Biological sex (0 = Female, 1 = Male) */
  PTGENDER: 0 | 1;
  /** Mini-Mental State Examination */
  MMSE: number;
  /** RAVLT Immediate Recall */
  RAVLT_immediate: number;
}

/* ======================================================
 * Output
 * Mirrors MCIScreeningOutput
 *
 * NOTE: predicted_class (binary HIGH_RISK_PROGRESSOR / LOW_RISK_MONITOR)
 * was removed by product decision — risk_category is the single primary
 * clinical read. `probabilities` below is retained as internal/audit
 * detail, not a clinical label, so its keys still reference the model's
 * internal class names.
 * ====================================================== */

export interface MCIScreeningOutput extends PredictionResponseBase {
  /** Optional patient identifier */
  patient_id?: string | number;
  /** Probability of progression within 24 months */
  progression_probability: number;
  /** Overall prediction confidence. Null until a calibrated metric exists. */
  confidence: number | null;
  /** Per-class probabilities (internal/audit detail) */
  probabilities: Record<"HIGH_RISK_PROGRESSOR" | "LOW_RISK_MONITOR", number>;
  /** Classification threshold */
  threshold_used: number;
  /** Clinical risk category */
  risk_category: MCIScreeningRiskCategory;
  /** Recommended clinical action */
  recommended_next_step: MCIScreeningRecommendedNextStep;
  /** Most influential features */
  top_features: string[];
  /** Public URL of the generated PDF report, if available */
  pdf_url?: string | null;
}